/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author david javax
 */
public class Nuevo extends javax.swing.JDialog {
//setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

private Modelo.Automata automataCreado; // 🔹 variable para guardar el autómata creado
    /**
     * Creates new form Nuevo
     */
public Nuevo(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    txtarea = new javax.swing.JTextArea();
    txtarea.setColumns(20);
    txtarea.setRows(10);
    jScrollPane1.setViewportView(txtarea);
    this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
//
//    setTitle("Nuevo Autómata AFD");
//
//    txtarea.setText(
//        "Simbolos: 0,1\n" +
//        "Estados: Q0,Q1,Q2,Q3\n" +
//        "Estado inicial: Q0\n" +
//        "Estados de aceptación: Q0\n" +
//        "Transiciones:\n" +
//        "Q2,Q1\n" +
//        "Q3,Q0\n" +
//        "Q0,Q3\n" +
//        "Q1,Q2\n" +
//        "Cadenas a analizar:\n" +
//        "1,0,0,1\n" +
//        "0,0,1,0,1\n"
//    );

}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnnuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel1.setText("AFD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        btnnuevo.setText("Guardar");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, 20));

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


public Modelo.Automata getAutomataCreado() {
    return automataCreado;
}


    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
         try {
        // Crear archivo temporal con el texto que el usuario escribió
        File temp = File.createTempFile("automata_manual", ".txt");
        BufferedWriter bw = new BufferedWriter(new FileWriter(temp));
        bw.write(txtarea.getText());
        bw.close();

        // Leer el automata usando tu clase ya existente
        Modelo.Automata automata = Modelo.LectorDeArchivo.leerDesdeArchivo(temp);

        // Guardar el automata como atributo de esta ventana
        this.automataCreado = automata;

        // Cerrar esta ventana
        JOptionPane.showMessageDialog(this, "Autómata creado correctamente.");
        this.dispose();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al procesar el texto: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnnuevoActionPerformed

//    public Nuevo(java.awt.Frame parent, boolean modal) {
//    this();
//    setLocationRelativeTo(parent);
//}
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Nuevo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}
