/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author moralesjs_
 */
public class VentanaP extends javax.swing.JFrame {

    /**
     * Creates new form VentanaP
     */
    public VentanaP() {
        initComponents();
        setTitle("Ventana Principal");
        btnImagenAutomata.setFocusPainted(false);
        btnImagenAutomata.setBorder(null);
        btnImagenAutomata.setOpaque(false);
        btnImagenAutomata.setContentAreaFilled(false);
       // this.setSize(750,600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
        setLocationRelativeTo(null);
        //  Establece el tamaño de la ventana (ancho, alto)
        this.setSize(800, 600);
        
      ; 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnImagenAutomata = new javax.swing.JButton();
        btnMenu1 = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtVistaPrevia = new javax.swing.JTextArea();
        Estados = new javax.swing.JLabel();
        Eaceptacion = new javax.swing.JLabel();
        Simbolos = new javax.swing.JLabel();
        Transiciones = new javax.swing.JLabel();
        txtEstados = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        miTablaAceptacion = new javax.swing.JTable();
        EInicial1 = new javax.swing.JLabel();
        txtEstadoInicial = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        miTablaTransiciones = new javax.swing.JTable();
        EInicial2 = new javax.swing.JLabel();
        txtSimbolos1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        miTablaAceptacion1 = new javax.swing.JTable();
        Simbolos1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setToolTipText("");

        btnMenu.setText("Menú");

        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Autómatas y Lenguajes Formales");

        btnImagenAutomata.setBackground(new java.awt.Color(204, 204, 255));
        btnImagenAutomata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/grafos.png"))); // NOI18N
        btnImagenAutomata.setBorderPainted(false);
        btnImagenAutomata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenAutomataActionPerformed(evt);
            }
        });

        btnMenu1.setText("Archivo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 235, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnMenu1)
                        .addGap(33, 33, 33)
                        .addComponent(btnMenu)
                        .addGap(31, 31, 31)
                        .addComponent(btnAbrir)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)))
                .addComponent(btnImagenAutomata)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenu)
                    .addComponent(btnMenu1)
                    .addComponent(btnAbrir))
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnImagenAutomata)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblEstado.setBackground(new java.awt.Color(0, 153, 0));
        lblEstado.setText("Estado:");

        txtVistaPrevia.setEditable(false);
        txtVistaPrevia.setColumns(20);
        txtVistaPrevia.setLineWrap(true);
        txtVistaPrevia.setRows(5);
        jScrollPane2.setViewportView(txtVistaPrevia);

        Estados.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Estados.setText("Estados:");

        Eaceptacion.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Eaceptacion.setText("Estado de aceptación:");

        Simbolos.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Simbolos.setText("Simbolos: ");

        Transiciones.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Transiciones.setText("Transiciones:");

        miTablaAceptacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null},
                {null, null}
            },
            new String [] {
                "No.", "Estados"
            }
        ));
        jScrollPane1.setViewportView(miTablaAceptacion);

        EInicial1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        EInicial1.setText("Estado Inicial:");

        miTablaTransiciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "0", "1"
            }
        ));
        jScrollPane3.setViewportView(miTablaTransiciones);
        if (miTablaTransiciones.getColumnModel().getColumnCount() > 0) {
            miTablaTransiciones.getColumnModel().getColumn(2).setHeaderValue("1");
        }

        EInicial2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        EInicial2.setText("Estado Final:");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        miTablaAceptacion1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null},
                {null, null}
            },
            new String [] {
                "No.", "Estados"
            }
        ));
        jScrollPane4.setViewportView(miTablaAceptacion1);

        Simbolos1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Simbolos1.setForeground(new java.awt.Color(255, 255, 255));
        Simbolos1.setText("Cadenas:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Simbolos1)
                        .addGap(0, 216, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Simbolos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblEstado))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Simbolos)
                                    .addComponent(Estados)
                                    .addComponent(EInicial1)
                                    .addComponent(EInicial2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSimbolos1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEstadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Transiciones)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Eaceptacion))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSimbolos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Simbolos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEstados)
                            .addComponent(Estados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EInicial1)
                            .addComponent(txtEstadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EInicial2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEstado)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Transiciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Eaceptacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(102, 102, 102))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImagenAutomataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenAutomataActionPerformed
        // TODO add your handling code here
        //JButton btnImagenAutomata = new JButton("Mi Botón");

    }//GEN-LAST:event_btnImagenAutomataActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setPreferredSize(new java.awt.Dimension(450, 350)); // tamaño más pequeño
        fileChooser.setLocation(this.getX(), this.getY());
        int resultado = fileChooser.showDialog(this, "Abrir");

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            if (archivoSeleccionado.getName().toLowerCase().endsWith(".txt")) {

                try (BufferedReader br = new BufferedReader(new FileReader(archivoSeleccionado))) {
                    StringBuilder contenido = new StringBuilder();
                    String linea;

                    while ((linea = br.readLine()) != null) {
                        contenido.append(linea).append("\n");
                    }

                    txtVistaPrevia.setText(contenido.toString());

                    lblEstado.setText("Archivo cargado exitosamente: " + archivoSeleccionado.getName());
                    lblEstado.setForeground(Color.GREEN);

                    String[] lineas = contenido.toString().split("\n");

                    String simbolos = "";
                    String estados = "";
                    String estadoInicial = "";
                    // String estadoAceptacion = "";
                    // String estadoAceptacion = "";
                    java.util.List<String> transiciones = new java.util.ArrayList<>();
                    java.util.List<String> estadoAceptacion = new java.util.ArrayList<>();
                    //java.util.List<String> estadoAceptacion = new java.util.ArrayList<>();

                    for (String l : lineas) {
                        l = l.trim();
                        if (l.startsWith("Simbolos:")) {
                            simbolos = l.replace("Simbolos:", "").trim();
                        } else if (l.startsWith("Estados:")) {
                            estados = l.replace("Estados:", "").trim();
                        } else if (l.startsWith("Estado inicial:")) {
                            estadoInicial = l.replace("Estado inicial:", "").trim();
                        } else if (l.toLowerCase().startsWith("estados de aceptación:")) {
                            String lineaE = l.substring(l.indexOf(":") + 1).trim(); // toma todo lo que sigue después de ":"
                            String[] partes = lineaE.split(",");
                            for (String p : partes) {
                                estadoAceptacion.add(p.trim());
                            }
                        } else if (l.startsWith("Transiciones:")){
                            // a partir de aquí vienen varias líneas, las guardamos
                        } else if (l.contains(",")) { // línea de transición, // Si la línea contiene una coma (',')
                            // Se asume que esta línea representa una transición (por ejemplo: "q0,q1,a")
                            // Se agrega esta línea a la lista o colección 'transiciones' para procesarla después
                            transiciones.add(l);
                        }
                    }

                    // SELECCION DE DATOS DEL TXT A SU RESPECTIVO LUGAR
                   // txtSimbolos.setText(simbolos);
                    txtEstados.setText(estados);
                    txtEstadoInicial.setText(estadoInicial);

                    // TABLA TRANSICIONES
                    String[] columnas = {"0", "1"};
                    DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

                    for (String t : transiciones) {
                        if(t.toLowerCase().contains("estado")|| t.toLowerCase().contains("aceptacion")){
                            continue;
                        }

                        String[] partes = t.split(",");
                        if (partes.length == 2) {
                            modelo.addRow(new Object[]{partes[0].trim(), partes[1].trim()});
                        }
                    }
                    miTablaTransiciones.setModel(modelo);

                    // TABLA ESTADOS DE ACEPTACIÓN
                    String[] columnasAceptacion = {"No.", "Estado"};
                    DefaultTableModel modeloAceptacion = new DefaultTableModel(columnasAceptacion, 0);

                    for (int i = 0; i < estadoAceptacion.size(); i++) {
                        modeloAceptacion.addRow(new Object[]{i + 1, estadoAceptacion.get(i)});
                    }

                    miTablaAceptacion.setModel(modeloAceptacion);

                } catch (IOException ex) {
                    lblEstado.setText("Error al leer el archivo.");
                    JOptionPane.showMessageDialog(this, "No se pudo abrir el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
                    lblEstado.setForeground(Color.RED);
                }
            } else {
                lblEstado.setText("El archivo no es válido. Solo se permiten .txt");
                lblEstado.setForeground(Color.RED);
                JOptionPane.showMessageDialog(this, "Formato no soportado. Seleccione un archivo .txt", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaP().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EInicial1;
    private javax.swing.JLabel EInicial2;
    private javax.swing.JLabel Eaceptacion;
    private javax.swing.JLabel Estados;
    private javax.swing.JLabel Simbolos;
    private javax.swing.JLabel Simbolos1;
    private javax.swing.JLabel Transiciones;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnImagenAutomata;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMenu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JTable miTablaAceptacion;
    private javax.swing.JTable miTablaAceptacion1;
    private javax.swing.JTable miTablaTransiciones;
    private javax.swing.JTextField txtEstadoInicial;
    private javax.swing.JTextField txtEstados;
    private javax.swing.JTextField txtSimbolos1;
    private javax.swing.JTextArea txtVistaPrevia;
    // End of variables declaration//GEN-END:variables
}
